---
apiVersion: v1
kind: Service
metadata:
  name: coherence-client
  labels:
    name: coherence-client
  namespace: coherence-demo
spec:
  ports:
    # the port that this service should serve on
  - port: 9000
    targetPort: 9000
  selector:
    name: coherence-client
