---
apiVersion: v1
kind: Service
metadata:
  name: coherence-server
  labels:
    name: coherence-server
  namespace: coherence-demo
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: coherence-server