---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: coherence-client
  labels:
    name: coherence-client
  namespace: coherence-demo
spec:
  replicas: 5
  template:
    metadata:
      labels:
        name: coherence-client
    spec:
      containers:
      - name: coherence-client
        image: caffeinatedexpert/docker-coherence:latest
        command: ["java"]
        args: ["-cp", "/u01/coherence-12.2.1.0.3.1.jar", "com.tangosol.net.MulticastTest", "-group", "224.0.0.1:9000", , "-packetSize", "1366", "-ttl", "4"]
        resources:
          limits:
            cpu: 300m
            memory: 2000Mi
          requests:
            cpu: 300m
            memory: 2000Mi
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux