---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: hazelcast-management-center
  namespace: hazelcast-demo
spec:
  replicas: 1
  template:
   metadata:
     labels:
       app: hazelcast-management-center
   spec:
     containers:
     - name: hazelcast
       image: hazelcast/management-center:3.9
