---
kind: Service
apiVersion: v1
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: hazelcast-management-center
  namespace: hazelcast-demo
spec:
  type: NodePort
  selector:
    app: hazelcast-management-center
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
