---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: management-center
spec:
  replicas: 1
  template:
   metadata:
     labels:
       app: management-center
   spec:
     containers:
     - name: hazelcast
       image: hazelcast/management-center
